### ISSUE TITLE
Is it possible integrate CGPR1 Qingping Motion & Light ?

### ISSUE THREAD

**Issue by itProfi** [bitkill/blea2mqtt#1]
Hello, there! Is it possible include support CGPR1 Qingping Motion & Light? In this page all matherial, include UUID, firmares and etc... https://pvvx.github.io/CGPR1/
https://pvvx.github.io/CGPR1/advs.log
https://pvvx.github.io/CGPR1/uuid.txt

**Comment by bitkill** [comment]
Hi, will review this in the weekend. I have no means of testing this though. Will ping you when a patch is done.

**Comment by itProfi** [comment]
Thank you! I have two this BLE motion sensors, and if i can help, say me..)

**Comment by itProfi** [comment]
That's another post from autor on russian forum, because he Russian. I need, i can try translate it
https://esp8266.ru/forum/threads/cgpr1-qingping-motion-light.5918/

**Comment by bitkill** [comment]
@itProfi Do you have a aliexpress link for this?

**Comment by itProfi** [comment]
> @itProfi Do you have a aliexpress link for this?

I buy 2 pcs 
https://aliexpress.ru/item/1005002345581399.html?spm=a2g39.orderlist.0.0.132e4aa6lOgK1M
